//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Journal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class discipline
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public discipline()
        {
            this.mark = new HashSet<mark>();
        }
    
        public int id_discipline { get; set; }
        public string Name_discipline { get; set; }
        public Nullable<int> id_group { get; set; }
        public Nullable<int> id_teacher { get; set; }
    
        public virtual group group { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mark> mark { get; set; }
    }
}
