//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Journal.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Journal_appEntities : DbContext
    {
        public Journal_appEntities()
            : base("name=Journal_appEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<discipline> discipline { get; set; }
        public virtual DbSet<group> group { get; set; }
        public virtual DbSet<mark> mark { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
