//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Journal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mark
    {
        public int id_mark { get; set; }
        public string Mark { get; set; }
        public string Date_mark { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public Nullable<int> id_student { get; set; }
    
        public virtual discipline discipline { get; set; }
        public virtual users users { get; set; }
    }
}
